version: '3.7'

services:
  
  stepbystep.database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=StepByStep
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stepbystep-network
  
  stepbystep.webapi:
    build:
     context: .
     dockerfile: StepByStep.Webapi/Dockerfile
    environment:
      STEPBYSTEP_CONN: Host=stepbystep.database;Port=5432;Database=StepByStep;User Id=postgres;Password=postgres;
    ports:
      - 8082:80
    networks:
      - stepbystep-network
    depends_on:
      - stepbystep.database
   

volumes:  
  pgdata:  

networks:
  stepbystep-network:

