version: '3.7'

services:
  stepbystep.webapi:
    image: ${DOCKER_REGISTRY-}stepbystepwebapi
    build:
      context: .
      dockerfile: StepByStep.WebApi/Dockerfile
    networks:
      - stepbystep-network

networks:
  stepbystep-network: