version: '3.7'

services:
  project-webapi:
    image: ${DOCKER_REGISTRY-}stepbystepwebapi
    build:
      context: .
      dockerfile: StepByStep.WebApi/Dockerfile
    networks:
      - project-net

networks:
  project-net: