version: '3.7'

services:
  stepbystep.webapi:    
    build:
      context: .
      dockerfile: StepByStep.Webapi/Dockerfile
    environment:
      CONN: Host=project-db.database;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - 8082:80      
    networks:
      - stepbystep-network
    depends_on:
      - project-db.database

  project-db.database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stepbystep-network

volumes:  
  pgdata:  

networks:
  stepbystep-network:
   
  
